### ISSUE TITLE
Programmable Controller crashing the server

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#710]
That one is quite nasty and easy to sum up: i started a rather basic drone program, put the drone in the controller, it went to fly and crashed the server. Same on server reboot and i had to use the "disable drone AI" on config to get back into the game (thanks a lot for that config by the way, it gave me a nice smile when i found it, as i feared having to rollback a whole day !).

Now for more details, the crash log: http://pastebin.com/DFXdiFiR
The drone program: http://pastebin.com/8jN2KEX8
And the little story:

I'm doing some flying platforms so the drones are quite handy on this. I set that one up to make a liquid plastic reserve, so the program works as above:

-import liquid from the thermopneumatic processing plant. It seemed to work.
-fly to a nearby platform with plenty of empty drums, here i set the liquid export to take the whole area, that allows to easily use stacks of drums as a big tank rather than make a single multiblock one, for more of an industrial feeling. The crash happened while the drone was on his way/reached the platform.
-once the drone is empty, it takes back liquid from the drums he just filled, then moves to another buffer drum near the plastic mixers to fill it
-the drone flies back to the platform to empty the remaining liquid plastic, then repeats the whole program.

The program isn't highly optimized, with the drone doing some useless steps probably, however it's a simple copy/paste from another program i use for oil. I just changed the coordinates, and the first one has been working fine for days. 

That's the most disturbing part as it's basically a copy/paste of the setup (same platform design, i took the coordinates in the same way, drums are the same, controllers are on the same pressure network, etc). I've been using the whole area drum import/export stuff for a while, even in previous games, so i'm a bit lost on what it could come from.

Also, the drone had no upgrades so far, i just wanted to check the program was working as intended.

Here is a screenshot of the setup for reference: http://pasteboard.co/116Lqi8G.png

The programmable controller is at the middle-top of the screen. On bottom left you can see the plastic processing platform (the drone goes to the last thermopneumatic plant of the line, on the right). He then goes to the platform with all the drums in the middle, and crashed around there. He's then supposed to fly back to the drum near the plastic mixers (actually hidden behind the first health point on my interface, oops).

As you can see things are quite close together, everything is chunkloaded and version 1.7.10-1.11.7-127. That's about all i can think about !

Also as a side note, did the drone programmer lose its "zoom out" feature ? I can't move the bar anymore or zoom in/out at all for some reason.

**Comment by GirafiStudios** [comment]
Update to latest version of PneumaticCraft.
I'm pretty sure this got fixed in PneumaticCraft-1.7.10-1.11.9-129

**Comment by Axylxys** [comment]
Indeed, i missed the latest updates, whoops.

It seems like it fixed it, though now i can't get the drones to work at all with the fluid import, doing some investigation on this.

**Comment by MineMaarten** [comment]
(Before reading your full post, I will though)
I know there's a problem with the Programmable Controllers atm, I was looking into it already. Just fyi :P

**Comment by Axylxys** [comment]
That's good to know, i totally can't get them to work so far with any import fluid or inventory, and was wondering if i'm missing something obvious or not. As for the first post, i guess it's irrelevant now as "programmable controllers not working at all" can be considered a fix to the server crash. :D 

I still can't get the zoom in/out on the programmer to work, though.

**Comment by MineMaarten** [comment]
The Programmable Controller refuses to jump back to Start with any program from what I can gather... That's the main issue.

**Comment by Axylxys** [comment]
The scrollbar doesn't work, either in the -127 version i had before, or the latest version. I have no idea if it comes from some config or something (i didn't change anything there) but it makes it so unpractical with long programs that i'm surprised nobody noticed it.

Also for the programmable controller, the explanation seems weird as i couldn't get it to even run through the first program pieces once when trying to use any import fluid/item. However, with a basic "go to" puzzle piece alone, it worked just fine.

So it seems it can run the "go to" at least, while the "import" fail from the very first time (the drone doesn't even appear at all).

**Comment by RViper80** [comment]
Confirming the zoom and scrollbar doesn't work, using version 135, in the Infinity FTB pack. Forge 1448

**Comment by GirafiStudios** [comment]
@RViper80 try with the latest version. A few bugs have been squashed with the programmable controller since version 135.

**Comment by RViper80** [comment]
Still no luck with version 138, neither the scrollbar nor the mouse wheel will zoom it.
